### ISSUE TITLE
Error :: Call to undefined function et_fb_enabled() :: v3.0.38

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#1102]
### Problem:
```
Error Call to undefined function et_fb_enabled() 
    antergos.com/wp-content/themes/Divi/includes/builder/framework.php:76 et_builder_load_modules_styles
    antergos.com/wp-includes/class-wp-hook.php:298 WP_Hook::apply_filters
    antergos.com/wp-includes/class-wp-hook.php:323 WP_Hook::do_action
    antergos.com/wp-includes/plugin.php:453 do_action
    antergos.com/wp-includes/script-loader.php:1221 wp_enqueue_scripts
    antergos.com/wp-includes/class-wp-hook.php:298 WP_Hook::apply_filters
    antergos.com/wp-includes/class-wp-hook.php:323 WP_Hook::do_action
    antergos.com/wp-includes/plugin.php:453 do_action
    antergos.com/wp-includes/general-template.php:2574 wp_head
    antergos.com/wp-content/themes/Divi/header.php:33 require_once
    antergos.com/wp-includes/template.php:684 load_template
    antergos.com/wp-includes/template.php:643 locate_template
    antergos.com/wp-includes/general-template.php:45 get_header
    antergos.com/wp-content/themes/Divi/404.php:1 include
    antergos.com/wp-content/plugins/wordfence/lib/wordfenceClass.php:6192 wordfence::preventAuthorNScans
    antergos.com/wp-includes/class-wp-hook.php:298 WP_Hook::apply_filters
    antergos.com/wp-includes/plugin.php:203 apply_filters
    antergos.com/wp-includes/class-wp.php:377 WP::parse_request
    antergos.com/wp-includes/class-wp.php:733 WP::main
    antergos.com/wp-includes/functions.php:955 wp
    antergos.com/wp-blog-header.php:16 require
    antergos.com/index.php:17 [main]
```

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1849

**Comment by timayhelen** [comment]
@lots0logs This might be fixed already. It's included in the latest Divi version as a hotfix if you want to test it:

https://github.com/elegantthemes/Divi-Beta/issues/1099

**Comment by lots0logs** [comment]
@timayhelen This is a different one. Its in the latest version actually (3.0.38)

**Comment by timayhelen** [comment]
@lots0logs Ok, just saying that 3.0.38 was released, and then a hotfix for that version was released again last night. So there are two 3.0.38 versions right now, one with the fix and one without it.

**Comment by lots0logs** [comment]
@timayhelen Oh okay, now I understand. Still this error occurs in a different file than the one we fixed recently :smiley:

**Comment by SlavaET** [comment]
This error occurs in case when plugin modifies the Wordpress loading flow by messing with the wp hooks. I was able to reproduce this issue  when Maintenance mode enabled in `All In One WP Security` plugin. This plugin hooks into the `wp_loaded` hook and loads the custom template with `wp_head()` which triggers scripts loading before all the required Divi components are loaded, therefore `et_fb_enabled()` is undefined at this point. It's impossible to predict the way 3rd party plugins may modify the WP hooks, so I simply added `function_exists` check to avoid this error, assuming that if `et_fb_enabled()` doesn't exists then we definitely not inside the VB.

### Steps to reproduce:
1) Install and activate `All In One WP Security` plugin;
2) Open WP Security -> Maintenance page;
3) Enable `Enable Front-end Lockout:`;
4) Log out from the Wordpress and try loading any page on the website. Error will appear right on the page.

**Comment by praveen-tast** [comment]
this error 
PHP Fatal error:  Call to undefined function et_fb_enabled() in /../../public_html/wp-content/themes/Divi/includes/builder/framework.php on line 224
the error still exist while using child theme, Please clarify the solution

**Comment by praveen-tast** [comment]
The Plugins I'm using are 
- Ninja Forms
- Yoast SEO
- Wordfence Security

**Comment by praveen-tast** [comment]
@FaycalBoutam 
I did the update of all the stuff as you defined, still this error occurs in my Multiple WordPress Project!

**Comment by uttc-admin** [comment]
I'm also getting this same error and have a child theme. Everything is up to date including Divi and all plugins. I also tried disabling plugins to see if there was a conflict. Error still occurs.

**Comment by alohascott** [comment]
Having the same issue as uttc-admin.

**Comment by alohascott** [comment]
I think WordFence is another plugin. Thanks Faycal!
