### ISSUE TITLE
Save Warning Appears In BB When It Contains Global Row

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#1103]
### Problem:

RE: #1094 though it appears only global rows cause the issue now.

### Additional Information
* https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=669395

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1853

**Comment by SlavaET** [comment]
Looks like it's fixed in 3.0.38. Reply from the customer:
> Yeah, it was on site with 3.0.37 version. After 3.0.38 it seems ok.

**Comment by SlavaET** [comment]
And I cannot reproduce it in the latest master. Warning doesn't appear for me. Tested with Global Rows on page and tried to replicate the cases we found/fixed earlier.

**Comment by timayhelen** [comment]
This still occurs for a lot of people, so it must be related to specific modules combinations. It also happens for me on our Divi Interior demo. I have exported the global section so you can reproduce the error on localhost (the layout is called Contact Footer and it's a Section layout type):

https://www.dropbox.com/s/1ypgnbh7891sxlg/Saving%20Test.json?dl=0

This needs to be imported via Divi Library > Import/Export.

One thing that's interesting to note is that if you take this global section after adding it to the page and confirmation the error, and then you Right Click > Disable Global and then Right Click > Save To Library and save as a new global section, the save warning goes away. 

![save-warning](https://cloud.githubusercontent.com/assets/3333028/24275858/db779bc4-0fef-11e7-8736-841be6ea6435.gif)

**Comment by SlavaET** [comment]
I see. It happens with Global Sections saved in older versions of Divi. There are some differences in order of attributes in shortcode and it causes the warning to appear, but once you open global section settings and save - attributes saved in correct order and the error goes away.
Looking for a solution.

**Comment by SlavaET** [comment]
I think I found reliable solution for this issue. Save warning may still appear in some cases but it won't appear anymore once user will hit "Update" or even without update in some cases. 
We can completely get rid of the warning only when/if we change the way BB works. If we move it to the FB platform, then the issue will be permanently fixed. But right now it uses the wp content to store the shortcode which is regenereated everytime module is changed and it causes the warning.

There are 2 situations when user will see the warning with my PR:
1. Page contains the global Sections or Rows which were saved in old version of Divi and doesn't contain all the attributes or contains them in different order. Once the page with such a module loaded Divi will update the Global module in DB, so it'll be saved with new correct attributes. If user will reload this page even without changes, then Save warning will appear, but it won't appear anymore even if user will force reload the page.
2) Page contains the global Sections or Rows which were updated from another page or from the library. In this case user will see the Save warning until page is updated because Divi always sync the content of Global Sections/Rows when the page is loaded. BB requires it, otherwise editing of global modules right from the page will not be possible.

To say it short, from the user's standpoint save warning will always disappear if "Update" button clicked.

@timayhelen with my PR you'll see the warning once you reload the page with old global Section and then it will never be displayed until you update the content of Global Section from another place in that case you'll need to press "Update" to get rid of the warning from particular page.

**Comment by Jronk** [comment]
@SlavaET please see PR review https://github.com/elegantthemes/submodule-builder/pull/1853#pullrequestreview-30925200

**Comment by Jronk** [comment]
I merged the PR, but if you could submit a follow up PR with the fix, that would be great, thanks!

**Comment by SlavaET** [comment]
@Jronk done. Here is the new PR - https://github.com/elegantthemes/submodule-builder/pull/1861
