### ISSUE TITLE
Icons Misaligned In Button-Option Fields

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#133]
## The Problem:

@ETDevTeam This is a small issue... but when using icons within `button-options` fields, the icons are not aligned correctly. They are postioned at the top of the button rather than vertically centered. The attached screen shots show the following:

**1.** A `button-options` field field with `divi/text-align-left`, `divi/text-align-center`, and `divi/text-align-right` icons. **(Incorrect)**
**2.** A `button-options` field field with `divi/align-left`, `divi/align-center`, and `divi/align-right` icons. **(Incorrect)**
**3.** The *Text Alignment* fields from the `font` group setting. **(Correct)**

![Image](https://github.com/user-attachments/assets/1b90d26d-2a98-4118-87a7-1860e127d28a)
![Image](https://github.com/user-attachments/assets/8d8fb1d8-0c25-4c4f-b845-3dc51febb246)
![Image](https://github.com/user-attachments/assets/bf2221c4-1db6-46b9-b0f3-f1c9dff48014)

**Comment by eduard-un** [comment]
Hey @dtcblyth, I have checked this on the latest Beta version, and everything seems to be aligned correctly on my end:

<img width="165" height="78" alt="Image" src="https://github.com/user-attachments/assets/abcabc45-ecd9-4b83-90ba-f2d2f78ff988" />

<img width="147" height="80" alt="Image" src="https://github.com/user-attachments/assets/029cb037-6188-44b1-a4c9-c007f46a58f6" />

Is it possible to let me know if those are specific to a particular module?

**Comment by dtcblyth** [comment]
Hi @eduard-un. The problem relates to custom `button-options` settings, as declared in the `module.json`. For example, the `button-options` below...
```
"alignHorz": {
  "groupType": "group-item",
  "item": {
    "label": "Tbl: Horizontal Alignment",
    "description": "Here you can set the horizontal alignment of table cell content. This setting can be adjusted per column under the <b>Column Settings > Design > Column Cells</b> toggle.",
    "groupSlug": "designTblTcellCell",
    "attrName": "tblTcellCell.advanced.alignHorz",
    "priority": 11,
    "render": true,
    "features": {
      "preset": [
        "style"
      ],
      "responsive": false,
      "hover": false,
      "sticky": false
    },
    "component": {
      "type": "field",
      "name": "divi/button-options",
      "props": {
        "allowClickToUnset": true,
        "options": {
          "left": {
            "icon": "divi/text-align-left"
          },
          "center": {
            "icon": "divi/text-align-center"
          },
          "right": {
            "icon": "divi/text-align-right"
          }
        }
      }
    }
  }
},
```
... displays like this...

<img width="400" height="281" alt="Image" src="https://github.com/user-attachments/assets/28f98a34-fd48-4fd0-9efc-ff0342bff2da" />

Checking the button’s CSS it has `padding: 0 4px;`, whereas native button-options have `padding: 3px;`.

<img width="400" height="333" alt="Image" src="https://github.com/user-attachments/assets/6a70e90c-1fa9-4cdf-84a8-e17ae8a298fa" />

I hope this helps.

**Comment by eduard-un** [comment]
@dtcblyth, based on the details you share, this seems to be an issue with 3Party plugins/modules, right? My previous check was done on native D5 modules. Is it possible to confirm this?

**Comment by dtcblyth** [comment]
@eduard-un Yes, exactly. This issue is related to custom settings in third-party modules.

**Comment by eduard-un** [comment]
@dtcblyth, awesome, thanks for the clarification. Going to report this internally so my colleagues can check this out.

**Comment by eduard-un** [comment]
@dtcblyth, this seems to have been fixed. 

If you get a chance, can you please check this:
1. Install and activate this plugin [divi-quick-module-v1.0.12.zip](https://github.com/user-attachments/files/24234232/divi-quick-module-v1.0.12.zip)
2. Add the Quick module in the VB
3. From the module settings → Content → Check button options below.

<img width="3418" height="1482" alt="Image" src="https://github.com/user-attachments/assets/dfb3013e-f5ff-4327-aba9-054ac80799e4" />

**Comment by dtcblyth** [comment]
@eduard-un Yes, it works on your _Quick Module_ but still not on my module. I have them both running on the same page and on your module the buttons display correctly, on mine they do not. The only differences I can see is that you have declared your `buttons-options` as _composable_ settings and I have declared mine in the `module.json` file. Also, my module is a parent/child module and yours is not.

**Comment by eduard-un** [comment]
@dtcblyth, those were the details we were looking to get. Thanks, mate. I will forward this to Ayub's team.
