### ISSUE TITLE
D5 responsive:: position absolute

### ISSUE THREAD

**Issue by elzadj** [elegantthemes/Divi-Beta#165]
### Problem Description
1. Describe what you did
Added a different offset for position on phone responsive. See steps to reproduce.

2. Describe what you expected to happen
Responsive offset for position absolute to work.

3. Describe what actually happened
transform css is inherited on phone responsive from desktop, and it breaks the offset

### Detailed Steps To Reproduce
Please provide a detailed list of exact steps that reproduce the issue.
1. Add a module, like Image or Text
2. Advanced > position > absolute > offset origin "centre centre"
3. Switch the divi editor from desktop to phone
4. Offset origin to left / right top / bottom
5. It's wrong both in the editor and frontend because the module has ```transform: translateY(-50%) translateX(-50%);``` from desktop.

### Screenshot and/or gif

<img width="2117" height="1275" alt="Image" src="https://github.com/user-attachments/assets/988098e4-ece5-4916-9502-7ed553170a99" />

### System Information
* Divi version: Divi 5.0.0-public-alpha.18.1
* Operating System: ubuntu / windows
* Browser: Chrome 138.0.7204.100
* PHP version: 8.2, 8.4
* Web Server: Apache / nginx
* WordPress version: 6.8.1

**Comment by eduard-un** [comment]
Hey @elzadj 👋 

This issue has been fixed. If possible, can you try to recheck it and let me know how it goes?

Thank you in advance!

**Comment by elzadj** [comment]
> Hey [@elzadj](https://github.com/elzadj) 👋
> 
> This issue has been fixed. If possible, can you try to recheck it and let me know how it goes?
> 
> Thank you in advance!

It's fixed, thank you!

**Comment by elzadj** [comment]
It looks like there is a regression in Divi 5.4.0, the bug is back. 

<img width="579" height="451" alt="Image" src="https://github.com/user-attachments/assets/c447f189-935a-4ff0-81a4-ce0a628238cd" />
