### ISSUE TITLE
FB :: Page settings :: Background Color settings disappear

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#331]
### Problem:

Under page settings if you open Section Background Color it disappears after 2-3 seconds. 
You can check the problem on the Testing page here: http://et.falgout.us/divi/?et_fb=1
![divi](https://cloud.githubusercontent.com/assets/3352130/18234351/9ffae088-730a-11e6-958e-f11e866ae510.gif)

I think the problem is related to fullwidth portfolio module. The settings disappear exactly when the slider transitions.

**Comment by timayhelen** [comment]
I also noticed that content background settings doesn't seem to work. The value doesn't appear to be saved for me.

**Comment by SlavaET** [comment]
These 2 issues are not related to each other, but I fixed both of them in my PR.

**Comment by timayhelen** [comment]
@SlavaET I still can't seem to get Content Area Background Color to work in the page settings. Does it work for you?

**Comment by SlavaET** [comment]
@timayhelen yes, it works fine for me. Make sure you adjusted opacity of the color, because it set to 0 by default:
![content-area-bg-works](https://cloud.githubusercontent.com/assets/3446682/18261183/ba68e00c-7416-11e6-916d-f047aef42a16.gif)

**Comment by rijendra** [comment]
This setting doesn't seem to work for me for Posts but works fine on Pages
