### ISSUE TITLE
Menu Suggestion

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#413]
I'm still having issues getting to some of the module settings from within visual builder.  On some small modules (i.e. buttons, dividers, single line text) the settings menu goes away before you can get your cursor to it.  My natural instinct then was to right click to see if there was another way to the menu.  Why not add "Module settings" to the right click menu to solve this problem?

**Comment by fikrirasyid** [comment]
@websbyjd can you post a screencast (you can use LiceCap: http://www.cockos.com/licecap/) and attach the exported layout here (you might need to zip it first)? We've fixed this issue previously, but you probably encounter an edge case we haven't found yet.

> Why not add "Module settings" to the right click menu to solve this problem

I think this is a good idea. @timayhelen what do you think?

**Comment by websbyjd** [comment]
I've attached the layout and a screencast.  The issue is with trying to edit the button settings

Here's the layout
[Divi Builder Layout.zip](https://github.com/elegantthemes/Divi-Beta/files/462273/Divi.Builder.Layout.zip)

Here's a screen cast:
[http://youtu.be/p25CFfXqAQE?hd=1](url)

**Comment by lots0logs** [comment]
@websbyjd This was improved in the latest version. Could you check it out and let us know if its still an issue? Thanks!
