### ISSUE TITLE
Plugin compatibility :: Ninja Forms & Formidable Forms :: Fatal Error When Previewing Forms

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#522]
### Problem:

Some customers get 
```
Fatal error: Call to undefined function et_builder_enqueue_font() in ...wp-content/themes/Divi/functions.php on line 194
```
with the plugin activated. Not sure if it's related to #390  

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=532544

**Comment by fikrirasyid** [comment]
@kary4 can you replicate the issue? Where exactly the error appears? I've tried replicated the issue and follows the step mentioned on the forum thread, but I still can't replicate the issue :|

**Comment by kary4** [comment]
@fikrirasyid  Is it a paid plugin, right? Can you send me your version? I'll try it locally.

**Comment by fikrirasyid** [comment]
@kary4 it is actually a free plugin. You can install it from WordPress plugin repository: https://wordpress.org/plugins/ninja-forms/

**Comment by kary4** [comment]
Ups, sorry.. I'll update you later.

**Comment by fikrirasyid** [comment]
No problem 👍

**Comment by lots0logs** [comment]
@fikrirasyid We were recently contacted by the developers of Formidable Forms regarding the same issue. The issue is a WSOD when previewing forms. I took a quick look at it and couldn't identify why that function isn't loaded  at the time its called. AFAICT the wp environment is being bootstrapped to the point where the builder's `functions.php` file (which contains the function listed in the error) should have been loaded.

Also of note, during my quick debugging of the issue I attempted to shim the builder fonts function just to see if it was the only problem. That revealed a different error; one which we've seen in the past related to compatibility issues with 3rd-party plugins:
```
PHP Fatal error:  Uncaught Error: Class 'ET_Global_Settings' not found in /srv/et.falgout.us/wp-content/themes/Divi/functions.php:7553
```

**Comment by lots0logs** [comment]
@uportnykh Could you let me know the status of this please? Thanks! :smile:

**Comment by uportnykh** [comment]
@lots0logs I've fixed the issue with Formidable Forms. It should fix the issue with other plugins that use an ajax request to preview changes. 

I can't replicate the issue with Ninja Popups plugin though.

**Comment by eduard-ungureanu** [comment]
@uportnykh I'm afraid that formidable plugin, still doesn't work, when I preview the form, I get a blank page with no errors.
