### ISSUE TITLE
Blog module :: Video post

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#615]
### Problem:

Video url appears in the post content.

### Steps To Reproduce:
1.  Create a post with video format
2.  Add this to the text editor `https://youtu.be/VUs_YrLvA0k` and publish
3. Check the blog module

![screenshot_5](https://cloud.githubusercontent.com/assets/9657712/19232262/9600331e-8f00-11e6-9934-493398c62986.png)

**Comment by lots0logs** [comment]
@Anny85 This doesnt appear to resolve the issue. Youtube video URL is still showing up:

![2016-10-12_02-54-06-pm](https://cloud.githubusercontent.com/assets/4675662/19325511/159f9006-908c-11e6-8e9e-d7d06ac87bde.png)

**Comment by Anny85** [comment]
@lots0logs I've just checked one more time. It works for me. Are you using Video post format for "Placeholder Video" post?

**Comment by lots0logs** [comment]
@Anny85 Yeah its a video post (otherwise the video thumbnail wouldnt be showing up for the post). I will take another look at it to make sure there isn't anything unusual at-play here and let you know.

**Comment by timayhelen** [comment]
@Anny85 It doesn't seem to work for me either.

**Comment by timayhelen** [comment]
Looks like it works when the blog module is set to Show Content, but not when it's set to Show Excerpt.

**Comment by Anny85** [comment]
@timayhelen @lots0logs I didn't realize the post should contain some text after the video URL to replicate the issue. I've fixed it.

**Comment by lots0logs** [comment]
@Anny85 I'm still seeing the video url for posts that have an HTML5 video (instead of youtube/vimeo). Not sure, but #630 might be related.

**Comment by Anny85** [comment]
@lots0logs It should be fixed now
