### ISSUE TITLE
BB :: Add Missing shortcuts for the Modules in BB

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#621]
### Problem:

- [x] Cut Module: <kbd>Super</kbd> + <kbd>X</kbd>
- [x] Copy Module: <kbd>Super</kbd> + <kbd>C</kbd>
- [x] Paste Module: <kbd>Super</kbd> + <kbd>V</kbd>
- [x] Disable Module: <kbd>D</kbd>
- [x] Lock Module: <kbd>L</kbd>
- [x] Change Column Structure <kbd>C</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - ... - 11 - changes the column structure of the current row being hovered over, or the parent row of the current module being hovered over.
- [x] Add New Row: <kbd>R</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - .... - 11 - Add a new row of specified column type below the current row or parent row being hovered over.
- [x] Add New Section: <kbd>S</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> - Add a new section of specified section type below the current section or parent section being hovered over. 1 = Regular, 2 = Specialty, 3 = Fullwidth.
- [x] Open Module Settings - Double Click on module.

**Comment by lots0logs** [comment]
@SlavaET 

* **Disable Module**:
  - [ ] I noticed there is a bit of a lag before the module actually looks disabled. Can we improve it?
* **Lock Module**:
  - [ ] This one isn't working for me.
  - [ ] I noticed that locking a module always results in an AJAX request to check if the user can lock the module. Is this intended? Couldn't we just cache the result of the first one?
* Add New Section:
  - [ ] Could we make the specialty section type modal respond to numbers being pressed to choose a section type? For example, if you wanted to add three specialty sections with the second type shown in the modal you could simply do <kbd>S</kbd>+<kbd>2</kbd>+<kbd>2</kbd> three times. Though maybe in that case we shouldn't involve the modal at all. @timayhelen what do you think?

**Comment by timayhelen** [comment]
#2 @lots0logs Locking seems to work for me. 

#3 We could add a new set of shortcuts for the Add New Row modal and the Specialty Section modal, where if you press any number by itself it selects and adds that column type (1,2,3,4,5,6,7,8,9,0,-, depending on the number of column types available.

**Comment by timayhelen** [comment]
@SlavaET I notice something strange about changing column types. Often types, if you don't move your move after changing a column type, the next hotkey you press to change the column type again wont work. Try pressing C+1, C+2, C+3, etc in a row without moving your mouse.

**Comment by lots0logs** [comment]
> We could add a new set of shortcuts for the Add New Row modal and the Specialty Section modal, where if you press any number by itself it selects and adds that column type (1,2,3,4,5,6,7,8,9,0,-, depending on the number of column types available.

That sounds good to me. Though it wouldn't allow for adding multiple row's with column type in a row. What I mean is, instead of doing this to add three new specialty sections with the second type: 

<kbd>S</kbd>+<kbd>2</kbd>+<kbd>2</kbd> , <kbd>2</kbd>

You would have to do this:

<kbd>S</kbd>+<kbd>2</kbd>+<kbd>2</kbd>, <kbd>S</kbd>+<kbd>2</kbd>+<kbd>2</kbd>

**Comment by SlavaET** [comment]
@lots0logs how can you press <kbd>2</kbd> + <kbd>2</kbd> ? Do you have two rows of number keys on your keyboard? :stuck_out_tongue:

**Comment by lots0logs** [comment]
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/19336994/16b44898-90d6-11e6-9922-94b5fef40146.gif)

Today has been one of those days :dizzy_face:  ... :laughing: I guess the only way to do it like I was imagining would be to start the columns/specialty types at the number three. I'm not sure about doing that though. What do you guys think?

**Comment by SlavaET** [comment]
- Fixed Disabling module lag.
- Added shortcuts to select the column structure if Columns Modal is opened ( keys 1 - 11 ). But it's quite difficult to guess which number to press, you need to count them and it makes the shortcut useless. We can probably add hints into that modal so it'll be easy to understand which button to press, like this:
![image](https://cloud.githubusercontent.com/assets/3446682/19341924/8359966c-9151-11e6-8fb4-034d24cfeb76.png)

- @timayhelen I improved the columns structure changing shortcut, it works as follows now:
if you hold <kbd> C </kbd> and press different numbers, then it'll change the columns structure without any lags/issues while mouse is not moved
If you press <kbd> C </kbd> + <kbd> 1 </kbd>, <kbd> C </kbd> + <kbd> 2 </kbd>, <kbd> C </kbd> + <kbd> 3 </kbd>, etc, then it'll work fine if you press them within 2 sec interval, if you press the next shortcut after 2 seconds, then it won't work until you hover over the module again. It's the way BB works, layout should be reinitiated after the column structure is changed to make sure all the module properties recalculated. Builder layout reinit means removing all the modules from the canvas and generating them again from the shortcode. Thus each module receives new ID and we cannot find the previously hovered module. It can only be improved if we rework the logic of BB and will not update the entire layout if one module was updated which is quite a significant change to the Builder. So, once you release the <kbd> C </kbd> Builder will reinit the layout with 2 seconds debounce. I think it should be enough.

@lots0logs I cannot reproduce the issue with `lock` shortcut, it works fine to me. As for the unwanted ajax calls - I think it's better to handle this in scope of different PR, since it's not related to the shortcuts actually.

**Comment by fikrirasyid** [comment]
@SlavaET VB's change row layout & add new layout uses the same layout order (1 ~ -). It is quite hard to remember indeed, but it is super easy to remember that 1: one columns, 2: two 1/2 columns, 3: three 1/3 columns, and 4: four 1/4 columns. The rest is kinda tricky 😅

**Comment by lots0logs** [comment]
@SlavaET The lock shortcut still doesnt work for me. There are no errors in the console. I can see that it makes the ajax request to check permissions and the response to the request is `true`.  

![2016-10-13 13-56](https://cloud.githubusercontent.com/assets/4675662/19362714/5e6031ee-914d-11e6-8a65-d4bbbdde3c59.gif)

**Comment by timayhelen** [comment]
Let's debug the issue with L not working for Dustin in a different ticket.
