### ISSUE TITLE
Elegant Themes subscription notice inside others plugin options.

### ISSUE THREAD

**Issue by bluantinoo** [elegantthemes/Divi-Beta#642]
### Problem:

I keep finding the notice of Elegant Themes subscriptions in places where it should not be.

Example: Popup Maker plugin options http://prntscr.com/cvs42m

**Comment by timayhelen** [comment]
Unfortunately it's not possible to add the notice to our update notifications only, so we try to word it in a way that makes sense for everything.

**Comment by bluantinoo** [comment]
tima maybe I've not been clear: I find update notification inside other plugins options.

**Comment by SlavaET** [comment]
Fixed. Below are the steps to reproduce this issue:
1) Install and activate `Popup Maker` plugin;
2) Go to `Popup Maker` -> `Add Popup`;
3) In the `Position` settings switch `Location` to `Top Left`;
4) Check the value in the new field.

@uportnykh can you please take a look at this fix? You originally developed this updating system, so I want to make sure my fix won't break it. 

@timayhelen this issue is not specific to Divi and we should update ALL of our themes with this fix.

**Comment by SlavaET** [comment]
Just want to mention - I performed some tests and my fix doesn't break our updating system, all the notifications displayed properly and updates work fine.

**Comment by lots0logs** [comment]
@timayhelen I tried testing it several times and even tried lowering the version to a number that was not previously used, but I could not get updates to show up. The updates still dont show up when I switch back to master branch. So I'm approving this based only on the fact that I don't think theses changes could break anything with the updates functionality.

**Comment by FaycalBoutam** [comment]
@SlavaET Could you check https://github.com/elegantthemes/Divi/issues/2596 as well? I still got the message after applying the fix.

**Comment by Jronk** [comment]
@FaycalBoutam I will check on it, im in the middle of review/merging, thanks for the update

**Comment by Jronk** [comment]
re-closing, as https://github.com/elegantthemes/Divi/issues/2596 was re-opened instead
