### ISSUE TITLE
Divi Builder :: Full Width Header :: scroll to next section

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#766]
### Problem:

The problem looks like the full width header in full screen mode doesn't positioned the scroll-down button if more the one full width header is placed in the page.

### Steps To Reproduce:
1) Change the primary and fixed menu heights to 40px.
2) Create a new page and insert 3 fullwidth sections.
3) Each fullwidth section should contain 3 full width headers.
4) Each fullwidth header should have the following settings:
- Make Fullscreen: Yes
- Show Scroll Down Button: Yes
- Use Parallax Effect: Yes (CSS Method)
5) the next section the scroll-to button cannot be seen and you have to scroll down to actually see it

I already prepare a layout:

[full width header.json.zip](https://github.com/elegantthemes/Divi-Beta/files/594775/full.width.header.json.zip)

Demo page:
http://divi.wordpress-corner.com/custom-layout-25/

**Comment by lots0logs** [comment]
@fikrirasyid This isn't working for me. Nothing happens when I click the button. Also, the section heights seem to be miscalculated as the button isnt visible in the viewport for any sections in the VB and its only visible for the first section on the page itself. 

### VB: Notice the button is not visible:
![2016-11-21_12-41-53-pm](https://cloud.githubusercontent.com/assets/4675662/20495952/c6dce12c-afe8-11e6-937e-e16af9f85a0f.png)

### Page: Button is visible for the first section but clicking it does nothing. No errors in console either.
![2016-11-21_12-42-28-pm](https://cloud.githubusercontent.com/assets/4675662/20495983/e903955c-afe8-11e6-8723-4609680bd33a.png)

### Page: Buttons not visible for sections after the first section:
![2016-11-21_12-43-12-pm](https://cloud.githubusercontent.com/assets/4675662/20496002/0330ff0a-afe9-11e6-8546-aba76ebbee78.png)

#### I checked to make sure that its not a cache issue:
![2016-11-21_12-50-46-pm](https://cloud.githubusercontent.com/assets/4675662/20496036/3244bb60-afe9-11e6-85d9-3e07e0096303.png)

**Comment by fikrirasyid** [comment]
@lots0logs can you share the following information:

- `/Divi`'s latest commit SHA
- `submodule-builder` latest commit SHA
- version of browser you're using

Furthermore, can you elaborate what do you mean by the following:

> This isn't working for me. Nothing happens when I click the button

I checked the PR on all of the following variations: 

Settings | Desktop | Tablet | Mobile
----|---------|--------|--------
Fixed Nav (standard)| Y | Y | Y
Fixed Nav (fixed nav height > initial nav height) | Y | Y | Y
Fixed Nav + Header style: centered | Y | Y | Y
Fixed Nav + Header style: centered inline logo | Y | Y | Y
Fixed Nav + Header style: slide in | Y | Y | Y
Fixed Nav + Header style: fullscreen | Y | Y | Y
Fixed Nav Deactivated | Y | Y | Y
Fixed Nav + rgba() main header | Y | Y | Y
Hide Nav | Y | Y | Y
Vertical Nav | Y | Y | Y

Do you mean the PR fails to work on all of the variations above, or only at fixed nav + header style: centered only? (Plus when the PR fails, did the nav is set to fixed, or non-fixed?).

The PR actually only fixes the issue on actual BB output and hasn't do anything on the VB due to the amount of variation that needs to be checked. I'm thinking of opening new issue for VB once we have all (at least most of) the possibilities handled well on the actual BB output. Do you think we need to do it on this PR anyway?

**Comment by lots0logs** [comment]
@fikrirasyid 

* **Divi:** `a3ef6eb3c3ee9f2ff09a837516aab400faafabc8`
* **Builder:** `d2dc0a21216977a6daf87a4d7711557447541879`
* **Browser:** Chrome 54.0.2840.100

>Do you mean the PR fails to work on all of the variations above, or only at fixed nav + header style: centered only? 

Clicking the button does not have any affect (the page doesn't scroll). This happens with fixed nav + default  header style and also with fixed nav + centered header style. I did not test other variations after those two didn't work.

> Do you think we need to do it on this PR anyway?

No, let's open a new Issue for the VB. We can worry about it after we finish with this one :+1:

**Comment by fikrirasyid** [comment]
@lots0logs noted, thank you for clarifying it. I'll look into it.

> No, let's open a new Issue for the VB. We can worry about it after we finish with this one 

Gotcha 👌

**Comment by fikrirasyid** [comment]
@lots0logs I've found out why the PR didn't work. I forgot to push and open the PR for its `Divi` counterpart :facepalm:. To review the PR, please checkout the following branches:

- Checkout `Divi` to `766-divi-builder-full-width-header-scroll-to-next-section` PR: https://github.com/elegantthemes/Divi/pull/2632
- Checkout `submodule-builder` to `766-divi-builder-full-width-header-scroll-to-next-section`. PR: https://github.com/elegantthemes/submodule-builder/pull/1449

**Comment by fikrirasyid** [comment]
@lots0logs can you elaborate why this is being moved back to `In Progress` pipeline?

**Comment by lots0logs** [comment]
@fikrirasyid Wow..sorry I could have sworn I posted a comment with screenshots. I might have posted them on another issue or PR by mistake :grimacing: 

The scroll button appears too far down the page in certain cases. I'm having trouble recalling exactly which variations it is but I do have the screenshots so they should help :sweat_smile: 

This is the second row on desktop view:

![2016-11-21_06-04-15-pm](https://cloud.githubusercontent.com/assets/4675662/20514255/8ca87dd2-b050-11e6-8867-6099e03803bd.png)
______________________

The next two are the first row for tablet and mobile:

![2016-11-21_06-06-15-pm](https://cloud.githubusercontent.com/assets/4675662/20514297/baaca596-b050-11e6-97df-be3f3f8e7354.png)
___________________________

![2016-11-21_06-06-44-pm](https://cloud.githubusercontent.com/assets/4675662/20514317/ce701748-b050-11e6-9197-72c7afa505dd.png)

**Comment by fikrirasyid** [comment]
@lots0logs can you take a look at it again? I think you're having issue on the following situation:

- fixed nav
- haeder style centered
- fixed nav height & line height: default values

There is one specific issue that occurs on header style centered: default header style's fixed nav height default value isn't exactly the default value of centered header style height. It appears that previously, the issue occurs if the fixed header height value doesn't changed but no issue appears if the page loads the modified fixed header height saved-on-customizer value.

I've updated fixed nav height default value for header style centered. It should look appropriate now.

**Comment by lots0logs** [comment]
@fikrirasyid Hmm..still seeing the same issue. To recap:

Scroll button position is partially outside of the viewport for:

* The first section on Tablet Portrait & Mobile with default, center, & inline header/nav layouts.
* Subsequent sections after the first section on Desktop for the centered and inline header/nav layouts.

**Comment by fikrirasyid** [comment]
@lots0logs can you try pull the the branches (note: the changes are on `/Divi` and `submodule-builder`) and test it again? I'm not sure how did you test it, but I test it on actual device and I found the issue occurs due to toolbar that can change its height when the page is being scrolled. 

If you're still seeing the issue, can you explain (as detail as possible) how did you test it and can you replicate the issue on this following URL?

- http://wordpress-8622-57086-151808.cloudwaysapps.com/766-1/
- http://wordpress-8622-57086-151808.cloudwaysapps.com/766-2/

I've tested the latest branch on the following actual devices:

- MBP 15" + El Capitan + Chrome 54.0.2840.98 (64-bit)
- iPad mini 2 + iOS 9.3.5 + Safari
- iPhone 6S + iOS 10.0.1 + Safari

I've tested it on BrowserStack as well. They look good.

**Comment by timayhelen** [comment]
@fikrirasyid 

1. If you load the page on mobile viewport, and then extend the browser window, the fullscreen module no longer goes fullscreen. Not sure if this is a new bug or not, but let's fix it in this PR:

![header](https://cloud.githubusercontent.com/assets/3333028/20733300/7d432d0e-b647-11e6-9463-12619eec0372.gif)

2. I tried using the Centered Header style, and I also increased the header height a bit in the customizer. I then added 4 fullwidth header modules to page and noticed that all header modules after the first header module have the incorrect heights:

![header2](https://cloud.githubusercontent.com/assets/3333028/20733402/0442dda4-b648-11e6-9941-85995d05fd23.gif)

**Comment by fikrirasyid** [comment]
@timayhelen

I've pushed https://github.com/elegantthemes/submodule-builder/commit/855c8b3466b7c6763c72b77d557410e540f0dd5c which should've fixed the issue. The incorrect height when resizing from mobile width to desktop width occurred because the adjustment is triggered too fast: it needs a slight timeout from window is done being resized to fullscreen height adjustment.

As in the second issue (centered header style), can you send me the layout as well? I've tried to mimic the screencast you attached above (no secondary nav, no sub-menu, no search icon, no WooCommerce cart, etc) but it looks as expected:

![766-pr](https://cloud.githubusercontent.com/assets/916442/20744112/8c4865ec-b70c-11e6-8543-5ae6ed134e8b.gif)

**Comment by timayhelen** [comment]
@fikrirasyid Did you increase the header height in the customizer as well as switch it to centered mode?

I have shared the layout in slack.

**Comment by fikrirasyid** [comment]
@timayhelen yeah, I've increased the header height in the customizer + switched it to centered mode.

Thanks. I'm currently working on it. Basically fixed nav height prediction isn't really accurate for centered header style. We might need to look for a better way to calculate fixed main header in centered header style 🤔

**Comment by fikrirasyid** [comment]
@timayhelen I've fixed the issue with centered header style + fixing dozens of issues on customizer related to fullscreen fullwidth header. I've tested the `submodule-builder` branch compatibility on Extra and Divi Builder as well. 

Regarding fullscreen fullwidth header on customizer, we might want to run more test to ensure that what is seen on customizer is equal to what is displayed on actual front end **WHEN** lots of options is modified and added without any refresh page. Nevertheless, it looks good now. The actual front end is even more solid.

The issue with centered header style is basically caused by the "prediction" approach used for "predicting" the height of fixed nav based on saved custom value. It turns out that this approach is  not reliable when centered header style is used. I ended up scrapped it and add more reliable solution for doing so: cloning, emulating and calculating fixed nav height with actual DOM. This turns out to be really reliable and accurate: This calculation even able to remove the "calculate offset as scroll next link is clicked" which makes the scroll animation when scroll next link is clicked to be even smoother.
