### ISSUE TITLE
Gallery Module :: Rerenders When Page Settings Modal Is Opened Once

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#839]
### Problem:

![2016-12-12 14-36](https://cloud.githubusercontent.com/assets/4675662/21115971/28bc907c-c079-11e6-8f0c-5ba2416ca037.gif)

### Attached PRs
https://github.com/elegantthemes/submodule-builder/pull/1513

**Comment by SlavaET** [comment]
Fixed. It's not related to the Gallery module. This will happen with any module which should be re-rendered on `previewWidth` change. Fullwidth portfolio, Map and some others for example.

**Comment by lots0logs** [comment]
@SlavaET I'm still seeing the same issue (just like in the screencast in my previous comment) I cleared my browser cache and triple checked that I had the correct branch built.

**Comment by SlavaET** [comment]
@lots0logs hm, probably you see a different issue.. Can I check it on your test website?

**Comment by lots0logs** [comment]
@SlavaET Sure, the test page I made is [here](http://et.falgout.us/divi/839-fix-initial-preview-width-value/).

**Comment by SlavaET** [comment]
@lots0logs I see the wrong output on your website ( when the page is loaded, BEFORE you open the Page Settings ), please check the screenshot:
![image](https://cloud.githubusercontent.com/assets/3446682/21213097/78dd77a2-c2bc-11e6-92aa-0f4e99ae2191.png)

I checked the code using the WPIDE on your website and it looks correct, but on the frontend it's not correct. Looks like js file was cached and is not updating. Can you please check it on localhost without any caching plugins? It should look like this:
 
![image](https://cloud.githubusercontent.com/assets/3446682/21213171/e756b446-c2bc-11e6-8fbd-545f1c3e2e6b.png)

**Comment by lots0logs** [comment]
@SlavaET I checked it again after making sure any possible cache was cleared. Before I open the page settings I see this:

![2016-12-19_03-03-55-pm](https://cloud.githubusercontent.com/assets/4675662/21329123/b6abb01a-c5fc-11e6-94cb-ae521c2be15a.png)

After opening the page settings, the gallery flashes just like in my screencast and then I see this:

![2016-12-19_03-05-34-pm](https://cloud.githubusercontent.com/assets/4675662/21329140/cf8bdd58-c5fc-11e6-891c-a727d684bf29.png)

**Comment by SlavaET** [comment]
@lots0logs fixed. Please check the latest version of PR.
