### ISSUE TITLE
VB :: Waypoints Throws An Uncaught Error When There Are Background Videos On Page

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#908]
### Problem:

https://github.com/elegantthemes/Divi-Beta/issues/822#issuecomment-274597321

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1620

**Comment by lceberg** [comment]
@lots0logs can you please provide the steps to reproduce this and/or a screencast ?

What I tried to reproduce this (on latest master):
![video-test](https://cloud.githubusercontent.com/assets/1928328/22242281/67385b28-e22b-11e6-87fc-d1e998da86ec.gif)

**Comment by lots0logs** [comment]
@lceberg 

![2017-01-24_03-47-38-pm](https://cloud.githubusercontent.com/assets/4675662/22268258/77ba942c-e24c-11e6-98d3-421078833256.png)

Here's the layout I'm using: https://www.dropbox.com/s/qtfah688tn5j31s/Divi%20Builder%20Layout%20%281%29.json?dl=1

**Comment by lots0logs** [comment]
@lceberg The video appears with black bars on the side in the VB (doesn't happen on the page itself).

![2017-01-25_06-33-52-pm](https://cloud.githubusercontent.com/assets/4675662/22315557/04b07582-e32d-11e6-86f7-238acc0ad4c3.png)

**Comment by lceberg** [comment]
@lots0logs I made some adjustments to the resizing logic, the videos should now be full-width in FB when the video height is higher than the window height. Can you please take a look at the PR once more ?

**Comment by lots0logs** [comment]
@lceberg Its okay now when you first load the builder but there are two issues that I found with it:

1. The video isn't adjusted when the tablet and mobile views are activated. 
2. If you DnD the section module to another place on the page, the issue with the black bars on each side the video occurs again.

**Comment by lceberg** [comment]
@lots0logs sorry for the delay, it seems when the visual editor is enabled the videos are handled a bit differently, so it took me some good time to debug. 😥

Your latest feedback is addressed.

**Comment by lots0logs** [comment]
@lceberg Please see my review. Also I'm seeing the following error in the browser console when the VB first loads. Everything appears to work fine though.
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```

**Comment by lceberg** [comment]
@lots0logs I addressed your feedback and cleaned the code a bit.

---

> Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

From what I found this seems to be a Chrome only bug ([#1](http://stackoverflow.com/questions/36803176/how-to-prevent-the-play-request-was-interrupted-by-a-call-to-pause-error), [#2](https://bugs.chromium.org/p/chromium/issues/detail?id=593273)). As it doesn't affect the functionality, do you think we should implement a workaround for it ?

**Comment by lots0logs** [comment]
@lceberg It looks like the workaround is pretty simple (checking if its paused before trying to play it) so let's go ahead and do it :+1:

**Comment by lceberg** [comment]
@lots0logs I implemented [this](http://stackoverflow.com/questions/36803176/how-to-prevent-the-play-request-was-interrupted-by-a-call-to-pause-error#answer-40370077) as it was the only solution that worked in that case. I can no longer see the warning, can you check it on your side ?

**Note:** there were some conflicts in `frontend-builder-scripts.js` caused by recent changes so in the end I had to manually apply all the changes from this PR to the master file, hence the last few commits.

**Comment by lots0logs** [comment]
@lceberg I'm still seeing the error in the VB and it results in the black bars on each side of the video. I debugged it a bit in the browser console and it looks like the problem is [this line](https://github.com/elegantthemes/submodule-builder/blob/master/frontend-builder/app/components/et-builder-section.jsx#L390) of the section module's `_initVideoBackground()` method. It results in us initializing mediaelement twice for each video background. If I'm right then we won't need the workaround after simply removing that line. :thinking:

**Comment by lceberg** [comment]
@lots0logs I removed that line and it seems videos work better on resize when in FB mode. I believe the issue with "The play() request was interrupted by a call to pause()." is caused by switching from play/pause too fast, but I can no longer reproduce it. Can you check if you still see it on your side after latest commit ?

**Comment by timayhelen** [comment]
@lceberg Can you merge master back into this PR? I want to test it with our latest updates.

**Comment by lceberg** [comment]
@timayhelen master is now merged into the PR.

I saw an issue with dragging and dropping videos that is present now. 😓 
Please let me know if you get the change to review and see anything else.

**Comment by lceberg** [comment]
@timayhelen Turns out I was dragging the element inside the section, instead the very section, which caused what I thought was an issue.

I merged master once more today, so you can test with the latest changes.
