### ISSUE TITLE
BlueHost :: Builder Sync :: Split testing not working on VB

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#932]
### Problem:

I see both variations one under the other, when saving the page with VB, I see the front end with both variations. I need to update/publish the page on the BB to see proper results on the front end, and reload the VB for it to work.

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1703

**Comment by fikrirasyid** [comment]
@FaycalBoutam can you verify that the following steps are correct to replicate the issue? I couldn't replicate the issue above except under the following steps. Thus, the fix submitted for this issue is made to fix the issue that appears on the following steps':

1. Open new builder
2. Add layout
3. Set split test
4. Right click the `Use Visual Builder` button
5. Open Visual builder on the new page / tab

**Comment by FaycalBoutam** [comment]
@fikrirasyid I'm not saving the page so right click on the VB button doesn't work for me. I fot 404 not found. 
Here's how I do my testing:
1 Open new page.
2 Use the Divi Builder.
3 LEFT click on the VB button.
4 Right click on the Edit page button on the admin bar. Now I have two tabs opened and I can use both BB and VB. 
5 Enable the Split testing.
6 Check the VB tab.

**Comment by timayhelen** [comment]
@fikrirasyid I see various issues with Split Testing. 

## Enabling Split Testing During Sync

1. Edit a page in the BB. 
2. Edit the same page in the VB in a new tab to initiate builder sync. 
3. Return to the BB tab and create a new split test. 
4. After the split test is created, return to the VB tab. It will sync, but it does not sync correctly. The variations are stacked up on top of each other, and there is no indication that they are split test variants. 

## Adding New Test Variants During Sync

1. Edit a page in the BB.
2. Create a split testing. 
3. Save the page and refresh the BB.
4. Now open up the VB in a new tab to initiate builder sync. 
5. In the BB, duplicate one of the split testing variations to add a third variant. 

The new variant will not be synced to the VB.

**Comment by fikrirasyid** [comment]
@FaycalBoutam @timayhelen thank you for clarifying it. I'm able to replicate the issue now. In essence, the issue occurs because post meta isn't being synced the way post_content is being synced using autosave. I'll take a look deeper into this 👍

**Comment by fikrirasyid** [comment]
@timayhelen @FaycalBoutam @Jronk I've updated the PR added on this ticket to fix the issues mentioned above (even more than the original ticket due to the scope of the issue found). Basically, this ticket's issue occurs due to:

- Absence of post meta autosave and sync
- Absence of proper data adjustment from BB to VB vice versa
- In general, absence of proper way to sync and autosave builder settings

https://github.com/elegantthemes/submodule-builder/pull/1703 adds proper *server-side* builder settings (not only split test) autosave and sync. It covers:

- correctly autosave & sync builder settings
- correctly autosave & sync split test

The PR fixes the issue mentioned on this ticket, but I found more issues and things that can be polished on this branch. After thinking about it, instead of fixing them all at once (it'll take time, for sure), I'll list things that still can be improved here. Let me know whether it'd be better to fix them at once on this PR or merge early + often to reduce the issues on the main branch:

- VB settings < BB settings, mainly on split testing fields. This causes an issue on the following scenario: a) BB: create split test, then open VB by right click + open on new tab, b) VB: do changes here, then save. This causes incomplete split testing attribute is being saved. I'm not saying we should add split test support right away on VB, but all settings needs to present on both builders + we can hide the UI if we prefer to.
- browser-backup for builder settings
- There are error thrown on console, but it appears to be an error which exists on main builder sync branch

**Comment by Jronk** [comment]
1. I vote at least for hidden UI as needed, but keeping all necessary split test attributes being saved in FB. then we can add the UI when we want, but solve the underlying issue right now much more easily.
2. Love it, I created a ticket for this https://github.com/elegantthemes/Divi-Beta/issues/965
3. What errors/ is there an issue for it already?

**Comment by fikrirasyid** [comment]
@Jronk thanks for the feedback. Thus:

1. Let's do it on this issue
2. Let's do it on #965 
3. I noticed various issues. After closer look, some of them are worth fixing on this issue and some other can be fixed on different ticket. 

These are the issues (worth fixing on this issue):
```
Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (invariant.js:39)
    at Dispatcher.dispatch (Dispatcher.js:167)
    at Object.moduleActive (et-builder-actions.js:32)
    at Constructor.componentDidUpdate (et-builder-module.jsx:459)
    at ReactCompositeComponentWrapper.invokeComponentDidUpdateWithTimer (ReactCompositeComponent.js:65)
    at CallbackQueue.notifyAll (CallbackQueue.js:67)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:81)
    at ReactReconcileTransaction.closeAll (Transaction.js:204)
    at ReactReconcileTransaction.perform (Transaction.js:151)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:138)
```

These are issues that probably would be better to be fixed on different ticket:

```
[10-Feb-2017 18:25:38 UTC] PHP Notice:  Undefined index: fullwidth in /Users/fmbpr/htdocs/elegantthemes/wp-content/themes/Divi/includes/builder/functions.php on line 764
[10-Feb-2017 18:25:38 UTC] PHP Notice:  Undefined index: specialty in /Users/fmbpr/htdocs/elegantthemes/wp-content/themes/Divi/includes/builder/functions.php on line 764
```

**Comment by fikrirasyid** [comment]
@Jronk @timayhelen I think https://github.com/elegantthemes/submodule-builder/pull/1703 is ready to be reviewed. It sync post meta as accurate as possible, even syncing post meta when builder settings modal is being opened.

One thing to be noted tho: VB sync everything as the value changes (so it is as real time as possible). BB, on the other hand, updates the value when modal settings is closed by clicking the save button (thus whatever changes made on builder settings on BB takes effect as soon as the modal is closed by clicking save button).

**Comment by lots0logs** [comment]
@fikrirasyid Following the steps from @timayhelen's first example [here](https://github.com/elegantthemes/Divi-Beta/issues/932#issuecomment-278453536), the VB gets stuck with the preloader showing though the split test subject appears correctly on the page. [Here's](https://gist.github.com/lots0logs/e7d3f5fc6b129682926a87b970f02bbf) the console output.

**Comment by fikrirasyid** [comment]
@lots0logs thanks for noticing that. I've pushed a fix for your feedback and the issue. I'm copying the commit message which fixes the issue for reference below.

***

https://github.com/elegantthemes/submodule-builder/commit/006006778ccd05822b6be4224f4b1fae37c44ffc

> # Builder Sync :: Split Test :: Fixed stacked split test subjects when syncing
>
> Fixing the issue appears on @lots0logs test at https://github.com/elegantthemes/Divi-Beta/issues/932#issuecomment-279448441 which is basically https://github.com/elegantthemes/Divi-Beta/issues/932#issuecomment-278453536.
> 
> This issue occurs in specific case, when subject status and subject lists are being synced on different `$_POST` and the latter **overwrite** the former. This can be consistently replicated by doing:
> 
> 1. Crate new page, activate builder. Open dev tools.
> 2. Add pre-defined layout.
> 3. Right click on `Use Visual Builder`. Open VB on different window / tab
> 4. Right click on any module, click `Split Test`. 
> 5. Blur from current window, then focusing on the dev tool. Wait for 2 seconds while BB is POST-ing/syncing the current state of builder (sync status is turned on and only a subject is set)
> 6. Go back / blur to BB window, now click any module to be split test's goal. Existing subject will be automatically duplicated.
> 7. Blur from current BB window, and focus on the VB window. The page will now sync and you'll see the stacked subject issue appears.
> 
> This occurs because the synced state on step 7 overwrites the already-synced-to-server-but-hasnt-synced-to-vb state on step 5.
> 
> To fix this, merge incoming new synced data a la `wp_parse_args()` instead of overwriting the old synced data. Let VB drops autosave once they have been used.

**Comment by Jronk** [comment]
https://github.com/elegantthemes/Divi-Beta/issues/965 has been fixed on same PR (see https://github.com/elegantthemes/submodule-builder/pull/1703/commits/e2053a99148300223436973237ee999a16f109ba)

**Comment by timayhelen** [comment]
@Jronk This fix no longer works at all for me after your recent changes. Split testing is not synced, nor are any other post meta settings.

**Comment by fikrirasyid** [comment]
@timayhelen I've pushed https://github.com/elegantthemes/submodule-builder/commit/462cb8477499441c5593051c04ac7399dbc7833a which should fix the issue. I think @Jronk needs to review it tho, since the issue is caused by recent refactoring and browser-based autosave mechanism:

1. Some code block is abstracted and not being called for BB. Thus, all BB to VB sync doesn't work
2. Some array element keys are being renamed, and some related array elements arent' being renamed.

**Comment by timayhelen** [comment]
@fikrirasyid @Jronk This still isn't working for me. Post meta is not being synced from the BB to the VB reliably. Starting a split testing in the BB and moving to the VB does not work.

**Comment by fikrirasyid** [comment]
@timayhelen @Jronk  I've fixed the post meta syncing issue on https://github.com/elegantthemes/submodule-builder/commit/7783be7f859b380b203b81f5c167c0f2725b19a3. I'm copying the commit message here for reference:

> The issue can be consistently replicated by doing the following:
> 
> 1. Open BB, load pre-defined layout. Open devtool > console. Right click and make sure that `Log XMLHttpRequest` is checked
> 2. Open visual builder on new page by right clicking + new window / tab on `Use visual builder` button
> 3. Configure split test: select subject, select goals, then hold on your cursor, don't move anywhere
> 4. Wait until AJAX call which carries heartbeat is triggered
> 5. After heartbeat is triggered, move to the VB window to trigger force autosave
> 6. You'll see that the split test subjects are being stacked
> 
> This issue occurs because:
> 
> - builder settings are appended on `heartbeatData.wp_autosave` (it becomes `heartbeatData.wp_autosave.builder_settings`) variable
> - `heartbeatData.wp_autosave` isn't being added on every heartbeat
> - `et_pb_value_updated` classname flag is being cleared on every heartbeat
> 
> Thus: everytime the heartbeat is triggered, the updated flags are being cleared, but not being added to heartbeat payload.
> 
> To fix it, only clear updated flag classname if the value has been added to heartbeat payload.

**Comment by lots0logs** [comment]
@fikrirasyid I'm seeing the following lines in the debug log and they appear to be directly related to the changes in this branch:
```
[22-Feb-2017 12:36:26 UTC] PHP Warning:  explode() expects parameter 2 to be string, array given in et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 3554
[22-Feb-2017 12:36:26 UTC] PHP Warning:  array_unique() expects parameter 1 to be array, null given in et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 3556
[22-Feb-2017 12:36:26 UTC] PHP Warning:  implode(): Invalid arguments passed in et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 3556
[22-Feb-2017 12:36:26 UTC] PHP Warning:  explode() expects parameter 2 to be string, array given in et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 1158
[22-Feb-2017 12:36:26 UTC] PHP Warning:  array_unique() expects parameter 1 to be array, null given in et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 1158
```

**Comment by fikrirasyid** [comment]
@lots0logs thank you for noticing it. I've submitted https://github.com/elegantthemes/submodule-builder/commit/000cc741ed2566ee8d2c808f8456e6bee17ac61a to fix that issue. I'm copying the commit message here for reference:

***

> The symptom of the bug is quite shocking: split test subjects are disappearing on VB. But essentially, the bug is caused by VB syncing subjects as array instead of string which causes `et_prevent_duplicate_item()` outputting `null` which causes VB incorrectly set `null` as array of subject which causes the disappearing subjects on VB (as reported later by @lots0logs at https://github.com/elegantthemes/Divi-Beta/issues/932#issuecomment-281658276).
> 
> While the nature of the bug appears to be simple, what's truly troublesome is find out the timing where this issue occurs. After countless attempts, the issue can be consistently replicated by doing exactly the following:
> 
> - Open new page editor, activate builder. Open dev tool > Console
> - Load `homepage-basic` pre-defined layout
> - Open VB on new window. Don't move the cursor to the new window, stay still
> - Right click the first slider on the first section, select `Split Test`
> - Select `Fullwidth Header` as goal
> - Switch to VB. Click anywhere to initiate focus. Wait until the sync process is done, indicated by the first slider turns into split test subjects. Right after the pre-loading disappears, switch back to BB. Click anywhere to initiate focus. Wait until pre-loader disappears. Hold on, wait until next heartbeat is triggered on VB (see the XMLHTTPRequest on console)
> - The subjects on VB disappears 
> 
>  ![all hopes are back](https://cloud.githubusercontent.com/assets/916442/23215573/7ce20f88-f945-11e6-912f-402bacedb832.gif)
>
> If you prefer a smooth screencast: https://www.dropbox.com/s/sj9bs5vhkakbs8e/disappearing%20subjects%20on%20builder%20sync.mov?dl=0
> 
>  This commit checks incoming subjects data comes from VB and format it into comma-separated string if needed.
