### ISSUE TITLE
"Use visual editor" leads to a blank page

### ISSUE THREAD

**Issue by yburshan** [elegantthemes/Divi-Beta#99]
### Problem:
Clicking on "Use visual editor" leads to a blank page, or just endlessly load.
This behavior is the same for drafts, or published posts, and for RTl and LTR aligned sited (i.e Hebrew and English.
I'm using  latest WP 4.6, multi-site setup, Divi is network enabled.

### Steps To Reproduce:
1.Edit page or post
2.Switch to divi builder
3.Add columns / rows and write something
4.Publish or save as draft
5. Click use visual editor

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Mac-book

**Operating System**: Win10 ENT

**Browser**: FF 48.0

**Screen Resolution**: 1366 x 768

**Screenshots**:
![2 use-visual-builder](https://cloud.githubusercontent.com/assets/21120198/17803626/46c363ee-6600-11e6-877b-4ef5170b45cf.png)
Then

![3 visual_builder_loading](https://cloud.githubusercontent.com/assets/21120198/17803640/5f18c2e0-6600-11e6-82b1-a7af8dd9f3e1.png)

-

**Comment by SlavaET** [comment]
@yburshan Can you try right clicking in Chrome and choosing "Inspect Element", refreshing the page and reproducing the error again?
Please see if any messages appear in the "Console" tab. Please paste the messages here if anything shows up.

**Comment by BrittanyAK** [comment]
I just saw this and commented on another post but this is exactly the same thing I am having issue with.  The site I put the beta on only has three plugins (Askmiet, Hello Dolly, DIvi Updater (I deactivated that))  Here is what Chrome shows in the console box on my end:

JQMIGRATE: Migrate is installed, version 1.4.1

My system is a PC, Windows 10.  Wordpress version is the most recent 4.6.

Thanks for looking into this

**Comment by yburshan** [comment]
Screenshot attached
I also get JQMIGRATE: Migrate is installed, version 1.4.1 message
The site is brand new multisite for testing.
I have the following plugins
* Easy Updates Manager
* Elegant Themes Divi Beta Tester
*Join My Multisite
*Limit Login Attempts
*Membership 2 Pro (Planning to try few things in memberships scenarios later).

![console_error](https://cloud.githubusercontent.com/assets/21120198/17830442/e5c22628-66d3-11e6-9320-82ee7cce4941.png)

**Comment by BrittanyAK** [comment]
Even after updating to the newest beta release (today), I still have a blank page (doesn't matter what browser)

**Steps To Reproduce:**
1.View page
2. Click on Visual Editor
3) just hangs with the four dots - nothing loads beyond that

**Comment by cap220** [comment]
Yep, same here but didn't even have the dots just a blank white page.

Also have a site where the beta is installed but the 'Visual Editor' is not available at all.

Both sites are single instance Divi site with child themes running WordPress 4.6, latest rev of Divi. problem occurs in all browsers (Chrome, FF, Safari, IE 11, Edge and on Win 10 Pro and OS X 10.X.

Plugins:

Akismet
BackWPUp
Bloom
CMS Tree Page View
Contact Form 7
DesktopServer for WordPress
Duplicator
ET Divi Beta Tester
Goo.gl
Google XML Sitemaps
Jetpack
Monarch
My Page Order
Post Types Order
Really Simple Captcha
Really Simple SSL
Wordfence
WordPress Importer

Uninstalled the Beta and reverted to just latest Divi.

**Comment by timayhelen** [comment]
@cap220 Can you try disabling all of your plugins and see if the issue persists? If so, please re-enable the plugins one by one and let us know which one caused the issue.

**Comment by yburshan** [comment]
Just updated to 2.9.12 and the visual editor still doesn't work.

**Comment by timayhelen** [comment]
@yburshan @cap220 @BrittanyAK Would you be able to install the Elegant Themes Support Plugin and then email me your support token and website URL to nick@elegantthemes.com so that I can log in a take a look?

http://www.elegantthemes.com/downloads/elegant-themes-support.zip

Please activate the plugin and generate a new token via the "Tools > Elegant Themes Support Account" page and email it to nick@elegantthemes.com. Include your website URL as well.

**Comment by BrittanyAK** [comment]
You betcha - sorry I got sick for the past few days so I have been laying
low.   Will do in the next 24 hours

-Brittany

**Comment by yburshan** [comment]
@timayhelen just sent you the token.
Sorry for the delay, I was traveling.

**Comment by BrittanyAK** [comment]
Nick, I just emailed you the token for you - still been sick.

**Comment by cap220** [comment]
Hey Nick...

An update from my issue, I reninstalled 2.9.x and it's working though when
I try to 'preview' (with WP preview) I get header images in post images
(instead of featured image) but it is not a problem in the Visual Builder
that, from all I've worked with it now on three different sites, works
flawlessly.

So, I think my incorrect preview issue would likely be a WP hiccup more
than a D 2.9.x issue.

Enjoying the beta immensely and thank you again for all the good work you
and your crew do!

Chris Potter

Phone: (847) 529-2813


This Email is covered by the Electronic Communications Privacy Act, 18
U.S.C. Sections 2510-2521 and is legally privileged. The information
contained in this Email is intended only for the use of the individual or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distributions or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify us by replying to this Email and
destroy the original message.

**Comment by timayhelen** [comment]
Thanks for providing your login details. It looks like all instances here were related to PHP memory limit. Increasing memory from 64mb to 128mb should fix the problem, and we will be integrating the builder failure modal to help diagnose these issues in the future.

**Comment by nadvolod** [comment]
Hello,
I'm also getting this problem now. The screen is just blank when I try to Enable Visual Builder. I increased the memory to 1024MB and still no luck.
Console Errors: http://prntscr.com/m9deqf
WP version: 5.0.3
PHP Memory: 1024MB
Divi version: not sure
